In [23]:
# NumPy
import numpy as np

# Dataframe operations
import pandas as pd

# Data visualization
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import Ridge

# Scalers
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.utils import shuffle

# Models
from sklearn.linear_model import LogisticRegression #logistic regression
from sklearn.linear_model import Perceptron
from sklearn import svm #support vector Machine
from sklearn.ensemble import RandomForestClassifier #Random Forest
from sklearn.neighbors import KNeighborsClassifier #KNN
from sklearn.naive_bayes import GaussianNB #Naive bayes
from sklearn.tree import DecisionTreeClassifier #Decision Tree
from sklearn.model_selection import train_test_split #training and testing data split
from sklearn import metrics #accuracy measure
from sklearn.metrics import confusion_matrix #for confusion matrix
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.neural_network import MLPClassifier

# Cross-validation
from sklearn.model_selection import KFold #for K-fold cross validation
from sklearn.model_selection import cross_val_score #score evaluation
from sklearn.model_selection import cross_val_predict #prediction
from sklearn.model_selection import cross_validate

# GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression

#Common Model Algorithms
from sklearn import svm, tree, linear_model, neighbors, naive_bayes, ensemble, discriminant_analysis, gaussian_process

#Common Model Helpers
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn import feature_selection
from sklearn import model_selection
from sklearn import metrics

#Visualization
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import seaborn as sns

In [24]:
conda install -c anaconda py-xgboost

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [282]:
train= pd.read_csv('train_.csv')
train['LotFrontage'].replace(np.nan, 0, regex=True,inplace=True)
train['Alley'].replace(np.nan, 'NA', regex=True,inplace=True)
train['MasVnrType'].replace(np.nan, 'None', regex=True,inplace=True)
train['MasVnrArea'].replace(np.nan, 0, regex=True,inplace=True)
train['BsmtQual'].replace(np.nan, 'None', regex=True,inplace=True)
train['BsmtCond'].replace(np.nan, 'None', regex=True,inplace=True)
train['BsmtExposure'].replace(np.nan, 'None', regex=True,inplace=True)
train['BsmtFinType1'].replace(np.nan, 'None', regex=True,inplace=True)
train['BsmtFinType2'].replace(np.nan, 'None', regex=True,inplace=True)
train['Electrical'].replace(np.nan, 'SBrkr', regex=True,inplace=True)
train['FireplaceQu'].replace(np.nan, 'None', regex=True,inplace=True)
train['GarageType'].replace(np.nan, 'None', regex=True,inplace=True)
train['GarageFinish'].replace(np.nan, 'None', regex=True,inplace=True)
train['GarageYrBlt'].replace(np.nan, 0, regex=True,inplace=True)
train['GarageQual'].replace(np.nan, 'None', regex=True,inplace=True)
train['GarageCond'].replace(np.nan, 'None', regex=True,inplace=True)
train['PoolQC'].replace(np.nan, 'None', regex=True,inplace=True)
train['Fence'].replace(np.nan, 'None', regex=True,inplace=True)
train['MiscFeature'].replace(np.nan, 'None', regex=True,inplace=True)
print(train.head())

   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave    NA      Reg
1   2          20       RL         80.0     9600   Pave    NA      Reg
2   3          60       RL         68.0    11250   Pave    NA      IR1
3   4          70       RL         60.0     9550   Pave    NA      IR1
4   5          60       RL         84.0    14260   Pave    NA      IR1

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0   None  None        None       0      2
1         Lvl    AllPub  ...        0   None  None        None       0      5
2         Lvl    AllPub  ...        0   None  None        None       0      9
3         Lvl    AllPub  ...        0   None  None        None       0      2
4         Lvl    AllPub  ...        0   None  None        None       0     12

  YrSold  SaleType  SaleCondition  SalePrice
0   2008        WD         Normal     208500
1   2007        WD         Normal     181500
2   2008        WD         Normal     223500
3   2006        WD        Abnorml     140000
4   2008        WD         Normal     250000

[5 rows x 81 columns]

In [283]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          1460 non-null   object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1460 non-null   object
 26  MasVnrArea     1460 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1460 non-null   object
 31  BsmtCond       1460 non-null   object
 32  BsmtExposure   1460 non-null   object
 33  BsmtFinType1   1460 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1460 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1460 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    1460 non-null   object
 58  GarageType     1460 non-null   object
 59  GarageYrBlt    1460 non-null   float64
 60  GarageFinish   1460 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1460 non-null   object
 64  GarageCond     1460 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         1460 non-null   object
 73  Fence          1460 non-null   object
 74  MiscFeature    1460 non-null   object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [284]:
train['LotShape'].value_counts()

Reg    925
IR1    484
IR2     41
IR3     10
Name: LotShape, dtype: int64

In [285]:
x=train.dtypes =='object'

In [286]:
obj=x[x==True]

In [287]:
train=train.join(pd.get_dummies(train[obj.index]))

In [288]:
num_train=train.drop(train[obj.index],axis=1)

In [289]:
num_train

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,0,0,1,0,0,0,0,1,0
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,0,0,0,1,0,0,0,0,1,0
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,0,0,1,0,0,0,0,1,0
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,0,0,1,1,0,0,0,0,0
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0,0,0,1,0,0,0,0,1,0
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,0,0,0,1,0,0,0,0,1,0
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0,0,0,1,0,0,0,0,1,0
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,0,0,0,1,0,0,0,0,1,0
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,0,0,0,1,0,0,0,0,1,0

In [290]:
label = LabelEncoder()
num_train['YearBuilt_code'] = label.fit_transform(num_train['YearBuilt'])
num_train['YearBuilt_code'] = num_train['YearBuilt_code'][:1460]
num_train['YearRemodAdd_code'] = label.fit_transform(num_train['YearRemodAdd'])
num_train['YearRemodAdd_code'] = num_train['YearRemodAdd_code'][:1460]
num_train['YrSold_code'] = label.fit_transform(num_train['YrSold'])
num_train['YrSold_code'] = num_train['YrSold_code'][:1460]
num_train['MoSold_code'] = label.fit_transform(num_train['MoSold'])
num_train['MoSold_code'] = num_train['MoSold_code'][:1460]
num_train=num_train.drop(num_train[['YearBuilt','YearRemodAdd','YrSold','MoSold']],axis=1)

In [291]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import RidgeCV
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [292]:
num_train

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,YearBuilt_code,YearRemodAdd_code,YrSold_code,MoSold_code
0,1,60,65.0,8450,7,5,196.0,706,0,150,...,0,0,0,0,1,0,104,53,2,1
1,2,20,80.0,9600,6,8,0.0,978,0,284,...,0,0,0,0,1,0,77,26,1,4
2,3,60,68.0,11250,7,5,162.0,486,0,434,...,0,0,0,0,1,0,102,52,2,8
3,4,70,60.0,9550,7,5,0.0,216,0,540,...,1,0,0,0,0,0,19,20,0,1
4,5,60,84.0,14260,8,5,350.0,655,0,490,...,0,0,0,0,1,0,101,50,2,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,0.0,0,0,953,...,0,0,0,0,1,0,100,50,1,7
1456,1457,20,85.0,13175,6,6,119.0,790,163,589,...,0,0,0,0,1,0,79,38,4,1
1457,1458,70,66.0,9042,7,9,0.0,275,0,877,...,0,0,0,0,1,0,44,56,4,4
1458,1459,20,68.0,9717,5,6,0.0,49,1029,0,...,0,0,0,0,1,0,51,46,4,3
1459,1460,20,75.0,9937,5,6,0.0,830,290,136,...,0,0,0,0,1,0,66,15,2,5

In [293]:
Y_train=num_train['SalePrice']
X_train=num_train.drop(num_train[['Id','SalePrice']],axis=1)

In [294]:
Y_train

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [295]:
X_train

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,...,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,YearBuilt_code,YearRemodAdd_code,YrSold_code,MoSold_code
0,60,65.0,8450,7,5,196.0,706,0,150,856,...,0,0,0,0,1,0,104,53,2,1
1,20,80.0,9600,6,8,0.0,978,0,284,1262,...,0,0,0,0,1,0,77,26,1,4
2,60,68.0,11250,7,5,162.0,486,0,434,920,...,0,0,0,0,1,0,102,52,2,8
3,70,60.0,9550,7,5,0.0,216,0,540,756,...,1,0,0,0,0,0,19,20,0,1
4,60,84.0,14260,8,5,350.0,655,0,490,1145,...,0,0,0,0,1,0,101,50,2,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,62.0,7917,6,5,0.0,0,0,953,953,...,0,0,0,0,1,0,100,50,1,7
1456,20,85.0,13175,6,6,119.0,790,163,589,1542,...,0,0,0,0,1,0,79,38,4,1
1457,70,66.0,9042,7,9,0.0,275,0,877,1152,...,0,0,0,0,1,0,44,56,4,4
1458,20,68.0,9717,5,6,0.0,49,1029,0,1078,...,0,0,0,0,1,0,51,46,4,3
1459,20,75.0,9937,5,6,0.0,830,290,136,1256,...,0,0,0,0,1,0,66,15,2,5

In [296]:
test= pd.read_csv('test_.csv')

In [297]:
test['LotFrontage'].replace(np.nan, 0, regex=True,inplace=True)
test['Alley'].replace(np.nan, 'NA', regex=True,inplace=True)
test['MasVnrType'].replace(np.nan, 'None', regex=True,inplace=True)
test['MasVnrArea'].replace(np.nan, 0, regex=True,inplace=True)
test['BsmtQual'].replace(np.nan, 'None', regex=True,inplace=True)
test['BsmtCond'].replace(np.nan, 'None', regex=True,inplace=True)
test['BsmtExposure'].replace(np.nan, 'None', regex=True,inplace=True)
test['BsmtFinType1'].replace(np.nan, 'None', regex=True,inplace=True)
test['BsmtFinType2'].replace(np.nan, 'None', regex=True,inplace=True)
test['Electrical'].replace(np.nan, 'SBrkr', regex=True,inplace=True)
test['FireplaceQu'].replace(np.nan, 'None', regex=True,inplace=True)
test['GarageType'].replace(np.nan, 'None', regex=True,inplace=True)
test['GarageFinish'].replace(np.nan, 'None', regex=True,inplace=True)
test['GarageYrBlt'].replace(np.nan, 0, regex=True,inplace=True)
test['GarageQual'].replace(np.nan, 'None', regex=True,inplace=True)
test['GarageCond'].replace(np.nan, 'None', regex=True,inplace=True)
test['PoolQC'].replace(np.nan, 'None', regex=True,inplace=True)
test['Fence'].replace(np.nan, 'None', regex=True,inplace=True)
test['MiscFeature'].replace(np.nan, 'None', regex=True,inplace=True)
test['MSZoning'].replace(np.nan, 'None', regex=True,inplace=True)
test['Utilities'].replace(np.nan, 'None', regex=True,inplace=True)
test['Exterior1st'].replace(np.nan, 'None', regex=True,inplace=True)
test['Exterior2nd'].replace(np.nan, 'None', regex=True,inplace=True)
test['BsmtFinSF1'].replace(np.nan, 0, regex=True,inplace=True)
test['BsmtFinSF2'].replace(np.nan, 0, regex=True,inplace=True)
test['BsmtUnfSF'].replace(np.nan, 0, regex=True,inplace=True)
test['TotalBsmtSF'].replace(np.nan, 0, regex=True,inplace=True)
test['BsmtFullBath'].replace(np.nan, 0, regex=True,inplace=True)
test['BsmtHalfBath'].replace(np.nan, 0, regex=True,inplace=True)
test['KitchenQual'].replace(np.nan, 'None', regex=True,inplace=True)
test['Functional'].replace(np.nan, 'None', regex=True,inplace=True)
test['GarageCars'].replace(np.nan, 0, regex=True,inplace=True)
test['GarageArea'].replace(np.nan, 0, regex=True,inplace=True)
test['SaleType'].replace(np.nan, 'None', regex=True,inplace=True)

In [298]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1459 non-null   object
 3   LotFrontage    1459 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          1459 non-null   object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1459 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1459 non-null   object
 24  Exterior2nd    1459 non-null   object
 25  MasVnrType     1459 non-null   object
 26  MasVnrArea     1459 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1459 non-null   object
 31  BsmtCond       1459 non-null   object
 32  BsmtExposure   1459 non-null   object
 33  BsmtFinType1   1459 non-null   object
 34  BsmtFinSF1     1459 non-null   float64
 35  BsmtFinType2   1459 non-null   object
 36  BsmtFinSF2     1459 non-null   float64
 37  BsmtUnfSF      1459 non-null   float64
 38  TotalBsmtSF    1459 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1459 non-null   float64
 48  BsmtHalfBath   1459 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1459 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1459 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    1459 non-null   object
 58  GarageType     1459 non-null   object
 59  GarageYrBlt    1459 non-null   float64
 60  GarageFinish   1459 non-null   object
 61  GarageCars     1459 non-null   float64
 62  GarageArea     1459 non-null   float64
 63  GarageQual     1459 non-null   object
 64  GarageCond     1459 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         1459 non-null   object
 73  Fence          1459 non-null   object
 74  MiscFeature    1459 non-null   object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1459 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

In [299]:
test=test.join(pd.get_dummies(train[obj.index]))
num_test=test.drop(train[obj.index],axis=1)

In [300]:
label = LabelEncoder()
num_test['YearBuilt_code'] = label.fit_transform(num_test['YearBuilt'])
num_test['YearBuilt_code'] = num_test['YearBuilt_code'][:1459]
num_test['YearRemodAdd_code'] = label.fit_transform(num_test['YearRemodAdd'])
num_test['YearRemodAdd_code'] = num_test['YearRemodAdd_code'][:1459]
num_test['YrSold_code'] = label.fit_transform(num_test['YrSold'])
num_test['YrSold_code'] = num_test['YrSold_code'][:1459]
num_test['MoSold_code'] = label.fit_transform(num_test['MoSold'])
num_test['MoSold_code'] = num_test['MoSold_code'][:1459]
num_test=num_test.drop(num_test[['Id','YearBuilt','YearRemodAdd','YrSold','MoSold']],axis=1)

In [301]:
test['Id']

0       1461
1       1462
2       1463
3       1464
4       1465
        ...
1454    2915
1455    2916
1456    2917
1457    2918
1458    2919
Name: Id, Length: 1459, dtype: int64

In [302]:
from sklearn.datasets import load_boston
from sklearn.ensemble import RandomForestRegressor
import numpy as np
#Load boston housing dataset as an example
rf = RandomForestRegressor()
rf.fit(X_train, Y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [303]:
importances = pd.Series(data=rf.feature_importances_,
                        index= X_train.columns)
importances_sorted = importances.sort_values()

In [304]:
important_index=importances_sorted[importances_sorted > 0.001].index

In [305]:
important_index

Index(['FireplaceQu_None', 'KitchenQual_Ex', 'BsmtFullBath', 'ScreenPorch',
       'BsmtExposure_Gd', 'ExterQual_Gd', 'BedroomAbvGr', 'MSSubClass',
       'YrSold_code', 'LotShape_Reg', 'CentralAir_N', 'MSZoning_RM',
       'GarageType_Attchd', 'CentralAir_Y', 'BsmtQual_Gd', 'GarageType_Detchd',
       'KitchenQual_Gd', 'Fireplaces', 'MoSold_code', 'BsmtQual_Ex',
       'WoodDeckSF', 'OverallCond', 'MasVnrArea', 'BsmtUnfSF', 'OpenPorchSF',
       'GarageYrBlt', 'TotRmsAbvGrd', 'LotFrontage', 'FullBath',
       'YearRemodAdd_code', 'YearBuilt_code', 'LotArea', 'GarageArea',
       'GarageCars', '1stFlrSF', 'BsmtFinSF1', '2ndFlrSF', 'TotalBsmtSF',
       'GrLivArea', 'OverallQual'],
      dtype='object')

In [306]:
X_train=X_train[important_index]
X_test=num_test[important_index]

In [307]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [308]:
from xgboost import XGBRegressor

In [309]:
from sklearn.metrics import mean_absolute_error
from xgboost import XGBRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

XGB = XGBRegressor(n_estimators=30,learning_rate=0.67)

# Fit the model
XGB.fit(X_train,Y_train) 
y_pred=XGB.predict(X_test)

[16:45:29] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

In [310]:
Y_train

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [311]:
X_train

array([[1.        , 0.        , 0.33333333, ..., 0.1400982 , 0.25923135,
        0.66666667],
       [0.        , 0.        , 0.        , ..., 0.20654664, 0.17483044,
        0.55555556],
       [0.        , 0.        , 0.33333333, ..., 0.15057283, 0.27354936,
        0.66666667],
       ...,
       [0.        , 0.        , 0.        , ..., 0.18854337, 0.37792012,
        0.66666667],
       [1.        , 0.        , 0.33333333, ..., 0.17643208, 0.14016579,
        0.44444444],
       [1.        , 0.        , 0.33333333, ..., 0.20556465, 0.17370008,
        0.44444444]])

In [312]:
X_train1, X_valid1, y_train1, y_valid1 = train_test_split(X_train, Y_train, random_state=0)
XGB = XGBRegressor(n_estimators=30,learning_rate=0.67)
lr = LinearRegression()
# Fit the model
XGB.fit(X_train1,y_train1) 
lr.fit(X_train1,y_train1) 
# Get predictions
pred_XGB = XGB.predict(X_valid1)
pred_lr = lr.predict(X_valid1)
# Calculate MAE
mae_XGB =  mean_absolute_error(pred_XGB,y_valid1)
mae_lr =  mean_absolute_error(pred_lr,y_valid1)
# Uncomment to print MAE
print("Mean Absolute Error XGB:" , mae_XGB)
print("Mean Absolute Error lr:" , mae_lr)

[16:45:30] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
Mean Absolute Error XGB: 21586.616042380138
Mean Absolute Error lr: 20172.502019643292

In [313]:
lr.fit(X_train,Y_train)
y_pred=lr.predict(X_test)

In [314]:
Y_train

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [315]:
y_pred

array([126269.94494768, 170895.05884633, 179059.79141905, ...,
       164122.05462781, 108714.71599387, 228265.45089627])

In [317]:
output = pd.DataFrame({'Id': test['Id'],
                       'SalePrice': y_pred})
output.to_csv('submission_sale_V13.csv', index=False)